export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        white: "var(--card)",
        "on-secondary": "#ffffff",
        "inverse-surface": "#332f32",
        primary: "var(--accent)",
        "on-primary": "#ffffff",
        "surface-tint": "#af2b3e",
        "on-tertiary-container": "#afa5a9",
        surface: "var(--surface)",
        "surface-container-high": "#ede6ea",
        "on-secondary-fixed-variant": "#842131",
        "on-surface": "var(--text)",
        "secondary-container": "#fe7e8a",
        "on-primary-container": "#ff828a",
        "surface-bright": "#fff7fb",
        "surface-dim": "#dfd8dc",
        secondary: "#a43947",
        "surface-container-low": "var(--surface-low)",
        "tertiary-fixed-dim": "#cfc4c8",
        "outline-variant": "var(--border)",
        "tertiary-container": "#423b3e",
        "surface-container-highest": "#e8e0e4",
        "primary-fixed": "#ffdada",
        outline: "#8c7071",
        "on-error-container": "#93000a",
        tertiary: "#2c2629",
        "on-surface-variant": "var(--muted)",
        "on-tertiary-fixed": "#201a1d",
        "error-container": "#ffdad6",
        background: "#fff7fb",
        "surface-container": "#f3ecf0",
        "on-secondary-fixed": "#40000d",
        "on-tertiary-fixed-variant": "#4c4548",
        "on-secondary-container": "#741527",
        "tertiary-fixed": "#ebdfe3",
        "surface-variant": "#e8e0e4",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ffb3b5",
        "on-primary-fixed-variant": "#8e0f28",
        "secondary-fixed": "#ffdadb",
        "primary-container": "#800020",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f6eff3",
        "on-background": "#1d1b1e",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#40000b",
        "secondary-fixed-dim": "#ffb2b7",
        "inverse-primary": "#ffb3b5",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "1.5rem",
        "space-xl": "2.5rem",
        "gutter-desktop": "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "margin-tablet": "2.5rem",
        margin: "1.25rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "margin-desktop": "4rem",
      },
      fontFamily: {
        "body-sm": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "headline-xl-mobile": ["Hanken Grotesk"],
        "label-meta": ["JetBrains Mono"],
        "label-badge": ["JetBrains Mono"],
        "body-lg": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "headline-xl": ["Hanken Grotesk"],
        "label-code": ["JetBrains Mono"],
        "headline-lg-mobile": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-sm": [
          "13px",
          { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" },
        ],
        "headline-lg": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "500" },
        ],
        "headline-xl-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "label-meta": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "400" },
        ],
        "label-badge": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" },
        ],
        "headline-sm": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "body-md": [
          "15px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-xl": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "600" },
        ],
        "label-code": [
          "13px",
          { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-lg-mobile": [
          "26px",
          { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
      },
    },
  },
};
